package com.turboquant.runtime.api;

import java.util.Arrays;

/**
 * Immutable result of one {@link ComputeSession#infer} call.
 *
 * <p>Contains the generated token IDs, the final-position logit distribution,
 * the wall-clock latency measured by the backend, and the backend's name for
 * attribution.</p>
 *
 * <p>Note: {@code lastLogits} is a dense float array of length {@code vocabSize}.
 * Backends may return an all-zero array as a placeholder until real kernels
 * are implemented.</p>
 */
public final class InferenceResult {

    private final int[]  generatedTokenIds;
    private final float[] lastLogits;
    private final int    promptTokenCount;
    private final int    generatedTokenCount;
    private final long   inferenceNanos;
    private final String backendName;
    private final String generatedText;

    private InferenceResult(Builder b) {
        this.generatedTokenIds  = Arrays.copyOf(b.generatedTokenIds, b.generatedTokenIds.length);
        this.lastLogits         = Arrays.copyOf(b.lastLogits, b.lastLogits.length);
        this.promptTokenCount   = b.promptTokenCount;
        this.generatedTokenCount = b.generatedTokenCount;
        this.inferenceNanos     = b.inferenceNanos;
        this.backendName        = b.backendName;
        this.generatedText      = b.generatedText;
    }

    /** The tokens generated by the model for this request. */
    public int[] generatedTokenIds() {
        return Arrays.copyOf(generatedTokenIds, generatedTokenIds.length);
    }

    /**
     * Logit distribution over the vocabulary at the last generated position.
     * Shape: {@code [vocabSize]}.  May be all-zeros for stub backends.
     */
    public float[] lastLogits() {
        return Arrays.copyOf(lastLogits, lastLogits.length);
    }

    /** Number of tokens in the input prompt. */
    public int promptTokenCount() {
        return promptTokenCount;
    }

    /** Number of tokens actually generated (may be &lt;= {@code request.maxNewTokens()}). */
    public int generatedTokenCount() {
        return generatedTokenCount;
    }

    /** Wall-clock inference duration measured inside the backend, in nanoseconds. */
    public long inferenceNanos() {
        return inferenceNanos;
    }

    /** Convenience: {@link #inferenceNanos} as milliseconds. */
    public double inferenceMillis() {
        return inferenceNanos / 1_000_000.0;
    }

    /** Name of the backend that produced this result (e.g. {@code "cpu-stub"}). */
    public String backendName() {
        return backendName;
    }

    /**
     * The generated text as a string, for text-native backends (e.g. llama.cpp).
     * May be {@code null} for token-based backends or stub backends.
     */
    public String generatedText() {
        return generatedText;
    }

    @Override
    public String toString() {
        return "InferenceResult{backend=" + backendName
                + ", promptTokens=" + promptTokenCount
                + ", generatedTokens=" + generatedTokenCount
                + ", latency=" + String.format("%.3f", inferenceMillis()) + "ms}";
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private int[]  generatedTokenIds  = new int[0];
        private float[] lastLogits        = new float[0];
        private int    promptTokenCount   = 0;
        private int    generatedTokenCount = 0;
        private long   inferenceNanos     = 0L;
        private String backendName        = "unknown";
        private String generatedText      = null;

        public Builder generatedTokenIds(int[] ids) {
            this.generatedTokenIds = ids;
            return this;
        }

        public Builder lastLogits(float[] logits) {
            this.lastLogits = logits;
            return this;
        }

        public Builder promptTokenCount(int n) {
            this.promptTokenCount = n;
            return this;
        }

        public Builder generatedTokenCount(int n) {
            this.generatedTokenCount = n;
            return this;
        }

        public Builder inferenceNanos(long ns) {
            this.inferenceNanos = ns;
            return this;
        }

        public Builder backendName(String name) {
            this.backendName = name;
            return this;
        }

        public Builder generatedText(String text) {
            this.generatedText = text;
            return this;
        }

        public InferenceResult build() {
            return new InferenceResult(this);
        }
    }
}
